FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig*.json ./
COPY prisma ./prisma
RUN npx prisma generate

CMD ["npx", "ts-node", "--transpile-only", "-P", "tsconfig.json", "prisma/seed.ts"]
